name: falcon_gcs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  google_maps_flutter: ^2.2.2
  camera: ^0.11.1
  flutter_compass: ^0.8.1
  fl_chart: ^0.70.2
  syncfusion_flutter_gauges: ^28.2.5
  dart_mavlink: ^0.1.0
  flutter_libserialport: ^0.5.0
  serial: ^0.0.7+1
  socket_io_client: ^3.1.2
  provider: ^6.1.5
  arcgis_map_sdk: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/compass.png
    - assets/images/needle.png
